export const templates: Record<string, any> = {
    first: {
        sound: '/Users/niktverd/code/shorts-cretor/source/sound/first.aac',
        images:[
            {path: '', loop: 0.33},
            {path: '', loop: 0.30},
            {path: '', loop: 0.30},
            {path: '', loop: 0.30},
            {path: '', loop: 0.30},
            {path: '', loop: 0.28},
            {path: '', loop: 0.62},
            {path: '', loop: 0.59},
            {path: '', loop: 0.14},
            {path: '', loop: 0.13},
            {path: '', loop: 0.35},
            {path: '', loop: 0.70},
        ],
    },
    second: {
        sound: '/Users/niktverd/code/shorts-cretor/source/sound/second.aac',
        images: [
            {path: '', loop: 0.27},
            {path: '', loop: 2.33},
            {path: '', loop: 0.20},
            {path: '', loop: 0.2},
            {path: '', loop: 0.21},
            {path: '', loop: 0.2},
            {path: '', loop: 0.84},
            {path: '', loop: 0.41},
            {path: '', loop: 0.38},
            {path: '', loop: 0.38},
            {path: '', loop: 0.41},
            {path: '', loop: 0.42},
            {path: '', loop: 0.41},
            {path: '', loop: 0.39},
            {path: '', loop: 0.8},
            {path: '', loop: 0.47},
            {path: '', loop: 0.62},
        ],
    },
    third: {
        sound: '/Users/niktverd/code/shorts-cretor/source/sound/third.aac',
        images: [
            {path: '', loop: 0.32},
            {path: '', loop: 0.5},
            {path: '', loop: 0.44},
            {path: '', loop: 0.5},
            {path: '', loop: 0.11},
            {path: '', loop: 0.24},
            {path: '', loop: 0.46},
            {path: '', loop: 0.46},
            {path: '', loop: 0.39},
            {path: '', loop: 0.54},
            {path: '', loop: 0.21},
            {path: '', loop: 0.23},
            {path: '', loop: 0.44},
            {path: '', loop: 0.23},
            {path: '', loop: 0.22},
            {path: '', loop: 0.43},
            {path: '', loop: 0.21},
            {path: '', loop: 0.2},
            {path: '', loop: 0.46},
            {path: '', loop: 0.24},
            {path: '', loop: 0.22},
            {path: '', loop: 0.21},
            {path: '', loop: 0.23},
            {path: '', loop: 0.43},
            {path: '', loop: 0.11},
            {path: '', loop: 0.13},
            {path: '', loop: 0.2},
            {path: '', loop: 0.36},
        ],
    },
    J6wGWuNIKE8: {
        sound: '/Users/niktverd/code/image-cropper/assets/audio/J6wGWuNIKE8.aac',
        images:[
            {path: '', loop: 1.27},
            {path: '', loop: 0.3},
            {path: '', loop: 0.34},
            {path: '', loop: 0.46},
            {path: '', loop: 0.17},
            {path: '', loop: 0.54},
            {path: '', loop: 0.31},
            {path: '', loop: 0.32},
            {path: '', loop: 0.43},
            {path: '', loop: 0.26},
            {path: '', loop: 0.2},
            {path: '', loop: 0.27},
            {path: '', loop: 0.33},
            {path: '', loop: 0.37},
            {path: '', loop: 0.43},
            {path: '', loop: 0.1},
            {path: '', loop: 0.57},
            {path: '', loop: 0.3},
            {path: '', loop: 0.34},
            {path: '', loop: 0.46},
            {path: '', loop: 0.24},
            {path: '', loop: 0.13},
            {path: '', loop: 0.1},
            {path: '', loop: 0.1},
            {path: '', loop: 0.15},
            {path: '', loop: 0.44},
            {path: '', loop: 0.43},
            {path: '', loop: 0.47},
            {path: '', loop: 0.46},
            {path: '', loop: 0.44},
            {path: '', loop: 0.46},
            {path: '', loop: 0.43},
        ],
    },
    Ar4rkQKtwug: {
        sound: '/Users/niktverd/code/image-cropper/assets/audio/Ar4rkQKtwug.aac',
        images:[
            {path: '', loop: 0.19},
            {path: '', loop: 0.45},
            {path: '', loop: 0.46},
            {path: '', loop: 0.52},
            {path: '', loop: 0.45},
            {path: '', loop: 0.46},
            {path: '', loop: 0.48},
            {path: '', loop: 0.48},
            {path: '', loop: 0.45},
            {path: '', loop: 0.44},
            {path: '', loop: 0.49},
            {path: '', loop: 0.48},
            {path: '', loop: 0.46},
            {path: '', loop: 0.43},
            {path: '', loop: 0.49},
            {path: '', loop: 0.48},
            {path: '', loop: 0.26},
        ],
    },
};
